title: Latinos in the Military
description: senior honors thesis
theme: jekyll-theme-slate
markdown: kramdown
url: "https://juliocedillo.github.io"
baseurl: "/military"
logo: "/assets/images/usa.webp"
